# Generated by Django 6.0.3 on 2026-03-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='university_nomi',
        ),
        migrations.AddField(
            model_name='university',
            name='university',
            field=models.CharField(default="Noma'lum universitet", max_length=200),
        ),
        migrations.AlterField(
            model_name='meningfamilyam',
            name='familya',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='meningismim',
            name='ism',
            field=models.CharField(max_length=100),
        ),
    ]
